micronaut:
    server:
        idle-timeout: 60m
        read-idle-timeout: 60m
        write-idle-timeout: 60m
        port: 8082
    http:
        client:
            read-timeout: 1m

    application:
        name: ia360-demo

    security:
        enabled: ${ENABLE_AUTH:true}
        authentication: idtoken
        oauth2:
            clients:
                keycloak:
                    client-id: ${KEYCLOAK_CLIENT_ID:demoClientId}
                    client-secret: ${KEYCLOAK_CLIENT_SECRET:JlqrdWhPhhIj738sr2OwPDJJiN93pV7U}
                    redirect-uri: http://localhost:8082/oauth/callback/keycloak
                    openid:
                        issuer: http://localhost:8080/realms/ai360-demo
        endpoints:
            logout:
                get-allowed: true
        redirect:
            login-success: /
            login-failure: /loginFailed
logger:
    levels:
        io.micronaut: TRACE
        com.demo: TRACE