// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: utils/protos/market.proto
// Protobuf Java Version: 4.35.0

package com.demo.proto.market;

@com.google.protobuf.Generated
public interface MarketMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:market.MarketMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.market.PositionMessage position = 1;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.market.PositionMessage position = 1;</code>
   * @return The position.
   */
  com.demo.proto.market.PositionMessage getPosition();
  /**
   * <code>.market.PositionMessage position = 1;</code>
   */
  com.demo.proto.market.PositionMessageOrBuilder getPositionOrBuilder();

  /**
   * <code>.market.QuoteMessage quote = 2;</code>
   * @return Whether the quote field is set.
   */
  boolean hasQuote();
  /**
   * <code>.market.QuoteMessage quote = 2;</code>
   * @return The quote.
   */
  com.demo.proto.market.QuoteMessage getQuote();
  /**
   * <code>.market.QuoteMessage quote = 2;</code>
   */
  com.demo.proto.market.QuoteMessageOrBuilder getQuoteOrBuilder();

  com.demo.proto.market.MarketMessage.MessageTypeCase getMessageTypeCase();
}
