// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: utils/protos/market.proto
// Protobuf Java Version: 4.35.0

package com.demo.proto.market;

@com.google.protobuf.Generated
public final class Market extends com.google.protobuf.GeneratedFile {
  private Market() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "Market");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_market_PositionMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_market_PositionMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_market_QuoteMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_market_QuoteMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_market_MarketMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_market_MarketMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031utils/protos/market.proto\022\006market\"\221\001\n\017" +
      "PositionMessage\022\021\n\taccountId\030\001 \001(\t\022\016\n\006sy" +
      "mbol\030\002 \001(\t\022\014\n\004side\030\003 \001(\t\022\014\n\004size\030\004 \001(\005\022\025" +
      "\n\ravgEntryPrice\030\005 \001(\t\022\021\n\tmarkPrice\030\006 \001(\t" +
      "\022\025\n\runrealizedPnL\030\007 \001(\t\"z\n\014QuoteMessage\022" +
      "\014\n\004type\030\001 \001(\t\022\016\n\006symbol\030\002 \001(\t\022\013\n\003bid\030\003 \001" +
      "(\t\022\013\n\003ask\030\004 \001(\t\022\014\n\004last\030\005 \001(\t\022\021\n\tvolume2" +
      "4h\030\006 \001(\003\022\021\n\ttimestamp\030\007 \001(\003\"r\n\rMarketMes" +
      "sage\022+\n\010position\030\001 \001(\0132\027.market.Position" +
      "MessageH\000\022%\n\005quote\030\002 \001(\0132\024.market.QuoteM" +
      "essageH\000B\r\n\013MessageTypeB\031\n\025com.demo.prot" +
      "o.marketP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_market_PositionMessage_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_market_PositionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_market_PositionMessage_descriptor,
        new java.lang.String[] { "AccountId", "Symbol", "Side", "Size", "AvgEntryPrice", "MarkPrice", "UnrealizedPnL", });
    internal_static_market_QuoteMessage_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_market_QuoteMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_market_QuoteMessage_descriptor,
        new java.lang.String[] { "Type", "Symbol", "Bid", "Ask", "Last", "Volume24H", "Timestamp", });
    internal_static_market_MarketMessage_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_market_MarketMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_market_MarketMessage_descriptor,
        new java.lang.String[] { "Position", "Quote", "MessageType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
