// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: utils/protos/market.proto
// Protobuf Java Version: 4.35.0

package com.demo.proto.market;

/**
 * Protobuf type {@code market.MarketMessage}
 */
@com.google.protobuf.Generated
public final class MarketMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:market.MarketMessage)
    MarketMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "MarketMessage");
  }
  // Use MarketMessage.newBuilder() to construct.
  private MarketMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MarketMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.demo.proto.market.Market.internal_static_market_MarketMessage_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.demo.proto.market.Market.internal_static_market_MarketMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.demo.proto.market.Market.internal_static_market_MarketMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.demo.proto.market.MarketMessage.class, com.demo.proto.market.MarketMessage.Builder.class);
  }

  private int messageTypeCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object messageType_;
  public enum MessageTypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    POSITION(1),
    QUOTE(2),
    MESSAGETYPE_NOT_SET(0);
    private final int value;
    private MessageTypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageTypeCase forNumber(int value) {
      switch (value) {
        case 1: return POSITION;
        case 2: return QUOTE;
        case 0: return MESSAGETYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageTypeCase
  getMessageTypeCase() {
    return MessageTypeCase.forNumber(
        messageTypeCase_);
  }

  public static final int POSITION_FIELD_NUMBER = 1;
  /**
   * <code>.market.PositionMessage position = 1;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return messageTypeCase_ == 1;
  }
  /**
   * <code>.market.PositionMessage position = 1;</code>
   * @return The position.
   */
  @java.lang.Override
  public com.demo.proto.market.PositionMessage getPosition() {
    if (messageTypeCase_ == 1) {
       return (com.demo.proto.market.PositionMessage) messageType_;
    }
    return com.demo.proto.market.PositionMessage.getDefaultInstance();
  }
  /**
   * <code>.market.PositionMessage position = 1;</code>
   */
  @java.lang.Override
  public com.demo.proto.market.PositionMessageOrBuilder getPositionOrBuilder() {
    if (messageTypeCase_ == 1) {
       return (com.demo.proto.market.PositionMessage) messageType_;
    }
    return com.demo.proto.market.PositionMessage.getDefaultInstance();
  }

  public static final int QUOTE_FIELD_NUMBER = 2;
  /**
   * <code>.market.QuoteMessage quote = 2;</code>
   * @return Whether the quote field is set.
   */
  @java.lang.Override
  public boolean hasQuote() {
    return messageTypeCase_ == 2;
  }
  /**
   * <code>.market.QuoteMessage quote = 2;</code>
   * @return The quote.
   */
  @java.lang.Override
  public com.demo.proto.market.QuoteMessage getQuote() {
    if (messageTypeCase_ == 2) {
       return (com.demo.proto.market.QuoteMessage) messageType_;
    }
    return com.demo.proto.market.QuoteMessage.getDefaultInstance();
  }
  /**
   * <code>.market.QuoteMessage quote = 2;</code>
   */
  @java.lang.Override
  public com.demo.proto.market.QuoteMessageOrBuilder getQuoteOrBuilder() {
    if (messageTypeCase_ == 2) {
       return (com.demo.proto.market.QuoteMessage) messageType_;
    }
    return com.demo.proto.market.QuoteMessage.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageTypeCase_ == 1) {
      output.writeMessage(1, (com.demo.proto.market.PositionMessage) messageType_);
    }
    if (messageTypeCase_ == 2) {
      output.writeMessage(2, (com.demo.proto.market.QuoteMessage) messageType_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (messageTypeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.demo.proto.market.PositionMessage) messageType_);
    }
    if (messageTypeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.demo.proto.market.QuoteMessage) messageType_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.demo.proto.market.MarketMessage)) {
      return super.equals(obj);
    }
    com.demo.proto.market.MarketMessage other = (com.demo.proto.market.MarketMessage) obj;

    if (!getMessageTypeCase().equals(other.getMessageTypeCase())) return false;
    switch (messageTypeCase_) {
      case 1:
        if (!getPosition()
            .equals(other.getPosition())) return false;
        break;
      case 2:
        if (!getQuote()
            .equals(other.getQuote())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageTypeCase_) {
      case 1:
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
        break;
      case 2:
        hash = (37 * hash) + QUOTE_FIELD_NUMBER;
        hash = (53 * hash) + getQuote().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.demo.proto.market.MarketMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.demo.proto.market.MarketMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.demo.proto.market.MarketMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.proto.market.MarketMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.demo.proto.market.MarketMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code market.MarketMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:market.MarketMessage)
      com.demo.proto.market.MarketMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.proto.market.Market.internal_static_market_MarketMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.proto.market.Market.internal_static_market_MarketMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.proto.market.MarketMessage.class, com.demo.proto.market.MarketMessage.Builder.class);
    }

    // Construct using com.demo.proto.market.MarketMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (positionBuilder_ != null) {
        positionBuilder_.clear();
      }
      if (quoteBuilder_ != null) {
        quoteBuilder_.clear();
      }
      messageTypeCase_ = 0;
      messageType_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.demo.proto.market.Market.internal_static_market_MarketMessage_descriptor;
    }

    @java.lang.Override
    public com.demo.proto.market.MarketMessage getDefaultInstanceForType() {
      return com.demo.proto.market.MarketMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.demo.proto.market.MarketMessage build() {
      com.demo.proto.market.MarketMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.demo.proto.market.MarketMessage buildPartial() {
      com.demo.proto.market.MarketMessage result = new com.demo.proto.market.MarketMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.demo.proto.market.MarketMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.demo.proto.market.MarketMessage result) {
      result.messageTypeCase_ = messageTypeCase_;
      result.messageType_ = this.messageType_;
      if (messageTypeCase_ == 1 &&
          positionBuilder_ != null) {
        result.messageType_ = positionBuilder_.build();
      }
      if (messageTypeCase_ == 2 &&
          quoteBuilder_ != null) {
        result.messageType_ = quoteBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.demo.proto.market.MarketMessage) {
        return mergeFrom((com.demo.proto.market.MarketMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.demo.proto.market.MarketMessage other) {
      if (other == com.demo.proto.market.MarketMessage.getDefaultInstance()) return this;
      switch (other.getMessageTypeCase()) {
        case POSITION: {
          mergePosition(other.getPosition());
          break;
        }
        case QUOTE: {
          mergeQuote(other.getQuote());
          break;
        }
        case MESSAGETYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageTypeCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetQuoteFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageTypeCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageTypeCase_ = 0;
    private java.lang.Object messageType_;
    public MessageTypeCase
        getMessageTypeCase() {
      return MessageTypeCase.forNumber(
          messageTypeCase_);
    }

    public Builder clearMessageType() {
      messageTypeCase_ = 0;
      messageType_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.demo.proto.market.PositionMessage, com.demo.proto.market.PositionMessage.Builder, com.demo.proto.market.PositionMessageOrBuilder> positionBuilder_;
    /**
     * <code>.market.PositionMessage position = 1;</code>
     * @return Whether the position field is set.
     */
    @java.lang.Override
    public boolean hasPosition() {
      return messageTypeCase_ == 1;
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     * @return The position.
     */
    @java.lang.Override
    public com.demo.proto.market.PositionMessage getPosition() {
      if (positionBuilder_ == null) {
        if (messageTypeCase_ == 1) {
          return (com.demo.proto.market.PositionMessage) messageType_;
        }
        return com.demo.proto.market.PositionMessage.getDefaultInstance();
      } else {
        if (messageTypeCase_ == 1) {
          return positionBuilder_.getMessage();
        }
        return com.demo.proto.market.PositionMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     */
    public Builder setPosition(com.demo.proto.market.PositionMessage value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageType_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }
      messageTypeCase_ = 1;
      return this;
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     */
    public Builder setPosition(
        com.demo.proto.market.PositionMessage.Builder builderForValue) {
      if (positionBuilder_ == null) {
        messageType_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      messageTypeCase_ = 1;
      return this;
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     */
    public Builder mergePosition(com.demo.proto.market.PositionMessage value) {
      if (positionBuilder_ == null) {
        if (messageTypeCase_ == 1 &&
            messageType_ != com.demo.proto.market.PositionMessage.getDefaultInstance()) {
          messageType_ = com.demo.proto.market.PositionMessage.newBuilder((com.demo.proto.market.PositionMessage) messageType_)
              .mergeFrom(value).buildPartial();
        } else {
          messageType_ = value;
        }
        onChanged();
      } else {
        if (messageTypeCase_ == 1) {
          positionBuilder_.mergeFrom(value);
        } else {
          positionBuilder_.setMessage(value);
        }
      }
      messageTypeCase_ = 1;
      return this;
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        if (messageTypeCase_ == 1) {
          messageTypeCase_ = 0;
          messageType_ = null;
          onChanged();
        }
      } else {
        if (messageTypeCase_ == 1) {
          messageTypeCase_ = 0;
          messageType_ = null;
        }
        positionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     */
    public com.demo.proto.market.PositionMessage.Builder getPositionBuilder() {
      return internalGetPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     */
    @java.lang.Override
    public com.demo.proto.market.PositionMessageOrBuilder getPositionOrBuilder() {
      if ((messageTypeCase_ == 1) && (positionBuilder_ != null)) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        if (messageTypeCase_ == 1) {
          return (com.demo.proto.market.PositionMessage) messageType_;
        }
        return com.demo.proto.market.PositionMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.market.PositionMessage position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.demo.proto.market.PositionMessage, com.demo.proto.market.PositionMessage.Builder, com.demo.proto.market.PositionMessageOrBuilder> 
        internalGetPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        if (!(messageTypeCase_ == 1)) {
          messageType_ = com.demo.proto.market.PositionMessage.getDefaultInstance();
        }
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.demo.proto.market.PositionMessage, com.demo.proto.market.PositionMessage.Builder, com.demo.proto.market.PositionMessageOrBuilder>(
                (com.demo.proto.market.PositionMessage) messageType_,
                getParentForChildren(),
                isClean());
        messageType_ = null;
      }
      messageTypeCase_ = 1;
      onChanged();
      return positionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.demo.proto.market.QuoteMessage, com.demo.proto.market.QuoteMessage.Builder, com.demo.proto.market.QuoteMessageOrBuilder> quoteBuilder_;
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     * @return Whether the quote field is set.
     */
    @java.lang.Override
    public boolean hasQuote() {
      return messageTypeCase_ == 2;
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     * @return The quote.
     */
    @java.lang.Override
    public com.demo.proto.market.QuoteMessage getQuote() {
      if (quoteBuilder_ == null) {
        if (messageTypeCase_ == 2) {
          return (com.demo.proto.market.QuoteMessage) messageType_;
        }
        return com.demo.proto.market.QuoteMessage.getDefaultInstance();
      } else {
        if (messageTypeCase_ == 2) {
          return quoteBuilder_.getMessage();
        }
        return com.demo.proto.market.QuoteMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     */
    public Builder setQuote(com.demo.proto.market.QuoteMessage value) {
      if (quoteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageType_ = value;
        onChanged();
      } else {
        quoteBuilder_.setMessage(value);
      }
      messageTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     */
    public Builder setQuote(
        com.demo.proto.market.QuoteMessage.Builder builderForValue) {
      if (quoteBuilder_ == null) {
        messageType_ = builderForValue.build();
        onChanged();
      } else {
        quoteBuilder_.setMessage(builderForValue.build());
      }
      messageTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     */
    public Builder mergeQuote(com.demo.proto.market.QuoteMessage value) {
      if (quoteBuilder_ == null) {
        if (messageTypeCase_ == 2 &&
            messageType_ != com.demo.proto.market.QuoteMessage.getDefaultInstance()) {
          messageType_ = com.demo.proto.market.QuoteMessage.newBuilder((com.demo.proto.market.QuoteMessage) messageType_)
              .mergeFrom(value).buildPartial();
        } else {
          messageType_ = value;
        }
        onChanged();
      } else {
        if (messageTypeCase_ == 2) {
          quoteBuilder_.mergeFrom(value);
        } else {
          quoteBuilder_.setMessage(value);
        }
      }
      messageTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     */
    public Builder clearQuote() {
      if (quoteBuilder_ == null) {
        if (messageTypeCase_ == 2) {
          messageTypeCase_ = 0;
          messageType_ = null;
          onChanged();
        }
      } else {
        if (messageTypeCase_ == 2) {
          messageTypeCase_ = 0;
          messageType_ = null;
        }
        quoteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     */
    public com.demo.proto.market.QuoteMessage.Builder getQuoteBuilder() {
      return internalGetQuoteFieldBuilder().getBuilder();
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     */
    @java.lang.Override
    public com.demo.proto.market.QuoteMessageOrBuilder getQuoteOrBuilder() {
      if ((messageTypeCase_ == 2) && (quoteBuilder_ != null)) {
        return quoteBuilder_.getMessageOrBuilder();
      } else {
        if (messageTypeCase_ == 2) {
          return (com.demo.proto.market.QuoteMessage) messageType_;
        }
        return com.demo.proto.market.QuoteMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.market.QuoteMessage quote = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.demo.proto.market.QuoteMessage, com.demo.proto.market.QuoteMessage.Builder, com.demo.proto.market.QuoteMessageOrBuilder> 
        internalGetQuoteFieldBuilder() {
      if (quoteBuilder_ == null) {
        if (!(messageTypeCase_ == 2)) {
          messageType_ = com.demo.proto.market.QuoteMessage.getDefaultInstance();
        }
        quoteBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.demo.proto.market.QuoteMessage, com.demo.proto.market.QuoteMessage.Builder, com.demo.proto.market.QuoteMessageOrBuilder>(
                (com.demo.proto.market.QuoteMessage) messageType_,
                getParentForChildren(),
                isClean());
        messageType_ = null;
      }
      messageTypeCase_ = 2;
      onChanged();
      return quoteBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:market.MarketMessage)
  }

  // @@protoc_insertion_point(class_scope:market.MarketMessage)
  private static final com.demo.proto.market.MarketMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.demo.proto.market.MarketMessage();
  }

  public static com.demo.proto.market.MarketMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MarketMessage>
      PARSER = new com.google.protobuf.AbstractParser<MarketMessage>() {
    @java.lang.Override
    public MarketMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MarketMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MarketMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.demo.proto.market.MarketMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

