// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: utils/protos/market.proto
// Protobuf Java Version: 4.35.0

package com.demo.proto.market;

@com.google.protobuf.Generated
public interface PositionMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:market.PositionMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountId = 1;</code>
   * @return The accountId.
   */
  java.lang.String getAccountId();
  /**
   * <code>string accountId = 1;</code>
   * @return The bytes for accountId.
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string side = 3;</code>
   * @return The side.
   */
  java.lang.String getSide();
  /**
   * <code>string side = 3;</code>
   * @return The bytes for side.
   */
  com.google.protobuf.ByteString
      getSideBytes();

  /**
   * <code>int32 size = 4;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>string avgEntryPrice = 5;</code>
   * @return The avgEntryPrice.
   */
  java.lang.String getAvgEntryPrice();
  /**
   * <code>string avgEntryPrice = 5;</code>
   * @return The bytes for avgEntryPrice.
   */
  com.google.protobuf.ByteString
      getAvgEntryPriceBytes();

  /**
   * <code>string markPrice = 6;</code>
   * @return The markPrice.
   */
  java.lang.String getMarkPrice();
  /**
   * <code>string markPrice = 6;</code>
   * @return The bytes for markPrice.
   */
  com.google.protobuf.ByteString
      getMarkPriceBytes();

  /**
   * <code>string unrealizedPnL = 7;</code>
   * @return The unrealizedPnL.
   */
  java.lang.String getUnrealizedPnL();
  /**
   * <code>string unrealizedPnL = 7;</code>
   * @return The bytes for unrealizedPnL.
   */
  com.google.protobuf.ByteString
      getUnrealizedPnLBytes();
}
