// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: utils/protos/market.proto
// Protobuf Java Version: 4.35.0

package com.demo.proto.market;

/**
 * Protobuf type {@code market.PositionMessage}
 */
@com.google.protobuf.Generated
public final class PositionMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:market.PositionMessage)
    PositionMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "PositionMessage");
  }
  // Use PositionMessage.newBuilder() to construct.
  private PositionMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PositionMessage() {
    accountId_ = "";
    symbol_ = "";
    side_ = "";
    avgEntryPrice_ = "";
    markPrice_ = "";
    unrealizedPnL_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.demo.proto.market.Market.internal_static_market_PositionMessage_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.demo.proto.market.Market.internal_static_market_PositionMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.demo.proto.market.Market.internal_static_market_PositionMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.demo.proto.market.PositionMessage.class, com.demo.proto.market.PositionMessage.Builder.class);
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accountId_ = "";
  /**
   * <code>string accountId = 1;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <code>string accountId = 1;</code>
   * @return The bytes for accountId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMBOL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIDE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object side_ = "";
  /**
   * <code>string side = 3;</code>
   * @return The side.
   */
  @java.lang.Override
  public java.lang.String getSide() {
    java.lang.Object ref = side_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      side_ = s;
      return s;
    }
  }
  /**
   * <code>string side = 3;</code>
   * @return The bytes for side.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSideBytes() {
    java.lang.Object ref = side_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      side_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 4;
  private int size_ = 0;
  /**
   * <code>int32 size = 4;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int AVGENTRYPRICE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object avgEntryPrice_ = "";
  /**
   * <code>string avgEntryPrice = 5;</code>
   * @return The avgEntryPrice.
   */
  @java.lang.Override
  public java.lang.String getAvgEntryPrice() {
    java.lang.Object ref = avgEntryPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avgEntryPrice_ = s;
      return s;
    }
  }
  /**
   * <code>string avgEntryPrice = 5;</code>
   * @return The bytes for avgEntryPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAvgEntryPriceBytes() {
    java.lang.Object ref = avgEntryPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avgEntryPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MARKPRICE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object markPrice_ = "";
  /**
   * <code>string markPrice = 6;</code>
   * @return The markPrice.
   */
  @java.lang.Override
  public java.lang.String getMarkPrice() {
    java.lang.Object ref = markPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      markPrice_ = s;
      return s;
    }
  }
  /**
   * <code>string markPrice = 6;</code>
   * @return The bytes for markPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMarkPriceBytes() {
    java.lang.Object ref = markPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      markPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNREALIZEDPNL_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object unrealizedPnL_ = "";
  /**
   * <code>string unrealizedPnL = 7;</code>
   * @return The unrealizedPnL.
   */
  @java.lang.Override
  public java.lang.String getUnrealizedPnL() {
    java.lang.Object ref = unrealizedPnL_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unrealizedPnL_ = s;
      return s;
    }
  }
  /**
   * <code>string unrealizedPnL = 7;</code>
   * @return The bytes for unrealizedPnL.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnrealizedPnLBytes() {
    java.lang.Object ref = unrealizedPnL_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unrealizedPnL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, accountId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(side_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, side_);
    }
    if (size_ != 0) {
      output.writeInt32(4, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(avgEntryPrice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, avgEntryPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(markPrice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, markPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unrealizedPnL_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, unrealizedPnL_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, accountId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(side_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, side_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(avgEntryPrice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, avgEntryPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(markPrice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, markPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unrealizedPnL_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, unrealizedPnL_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.demo.proto.market.PositionMessage)) {
      return super.equals(obj);
    }
    com.demo.proto.market.PositionMessage other = (com.demo.proto.market.PositionMessage) obj;

    if (!getAccountId()
        .equals(other.getAccountId())) return false;
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getSide()
        .equals(other.getSide())) return false;
    if (getSize()
        != other.getSize()) return false;
    if (!getAvgEntryPrice()
        .equals(other.getAvgEntryPrice())) return false;
    if (!getMarkPrice()
        .equals(other.getMarkPrice())) return false;
    if (!getUnrealizedPnL()
        .equals(other.getUnrealizedPnL())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + getSide().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + AVGENTRYPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getAvgEntryPrice().hashCode();
    hash = (37 * hash) + MARKPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getMarkPrice().hashCode();
    hash = (37 * hash) + UNREALIZEDPNL_FIELD_NUMBER;
    hash = (53 * hash) + getUnrealizedPnL().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.demo.proto.market.PositionMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.demo.proto.market.PositionMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.demo.proto.market.PositionMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.proto.market.PositionMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.demo.proto.market.PositionMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code market.PositionMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:market.PositionMessage)
      com.demo.proto.market.PositionMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.proto.market.Market.internal_static_market_PositionMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.proto.market.Market.internal_static_market_PositionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.proto.market.PositionMessage.class, com.demo.proto.market.PositionMessage.Builder.class);
    }

    // Construct using com.demo.proto.market.PositionMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accountId_ = "";
      symbol_ = "";
      side_ = "";
      size_ = 0;
      avgEntryPrice_ = "";
      markPrice_ = "";
      unrealizedPnL_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.demo.proto.market.Market.internal_static_market_PositionMessage_descriptor;
    }

    @java.lang.Override
    public com.demo.proto.market.PositionMessage getDefaultInstanceForType() {
      return com.demo.proto.market.PositionMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.demo.proto.market.PositionMessage build() {
      com.demo.proto.market.PositionMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.demo.proto.market.PositionMessage buildPartial() {
      com.demo.proto.market.PositionMessage result = new com.demo.proto.market.PositionMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.demo.proto.market.PositionMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accountId_ = accountId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.side_ = side_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.avgEntryPrice_ = avgEntryPrice_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.markPrice_ = markPrice_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.unrealizedPnL_ = unrealizedPnL_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.demo.proto.market.PositionMessage) {
        return mergeFrom((com.demo.proto.market.PositionMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.demo.proto.market.PositionMessage other) {
      if (other == com.demo.proto.market.PositionMessage.getDefaultInstance()) return this;
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSide().isEmpty()) {
        side_ = other.side_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (!other.getAvgEntryPrice().isEmpty()) {
        avgEntryPrice_ = other.avgEntryPrice_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getMarkPrice().isEmpty()) {
        markPrice_ = other.markPrice_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getUnrealizedPnL().isEmpty()) {
        unrealizedPnL_ = other.unrealizedPnL_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              accountId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              side_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              size_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              avgEntryPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              markPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              unrealizedPnL_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object accountId_ = "";
    /**
     * <code>string accountId = 1;</code>
     * @return The accountId.
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accountId = 1;</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accountId = 1;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accountId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string accountId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      accountId_ = getDefaultInstance().getAccountId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string accountId = 1;</code>
     * @param value The bytes for accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accountId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 2;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object side_ = "";
    /**
     * <code>string side = 3;</code>
     * @return The side.
     */
    public java.lang.String getSide() {
      java.lang.Object ref = side_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        side_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string side = 3;</code>
     * @return The bytes for side.
     */
    public com.google.protobuf.ByteString
        getSideBytes() {
      java.lang.Object ref = side_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        side_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string side = 3;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      side_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string side = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      side_ = getDefaultInstance().getSide();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string side = 3;</code>
     * @param value The bytes for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      side_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 4;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 4;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {

      size_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      size_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object avgEntryPrice_ = "";
    /**
     * <code>string avgEntryPrice = 5;</code>
     * @return The avgEntryPrice.
     */
    public java.lang.String getAvgEntryPrice() {
      java.lang.Object ref = avgEntryPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avgEntryPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string avgEntryPrice = 5;</code>
     * @return The bytes for avgEntryPrice.
     */
    public com.google.protobuf.ByteString
        getAvgEntryPriceBytes() {
      java.lang.Object ref = avgEntryPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avgEntryPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string avgEntryPrice = 5;</code>
     * @param value The avgEntryPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAvgEntryPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      avgEntryPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string avgEntryPrice = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgEntryPrice() {
      avgEntryPrice_ = getDefaultInstance().getAvgEntryPrice();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string avgEntryPrice = 5;</code>
     * @param value The bytes for avgEntryPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAvgEntryPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      avgEntryPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object markPrice_ = "";
    /**
     * <code>string markPrice = 6;</code>
     * @return The markPrice.
     */
    public java.lang.String getMarkPrice() {
      java.lang.Object ref = markPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        markPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string markPrice = 6;</code>
     * @return The bytes for markPrice.
     */
    public com.google.protobuf.ByteString
        getMarkPriceBytes() {
      java.lang.Object ref = markPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        markPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string markPrice = 6;</code>
     * @param value The markPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMarkPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      markPrice_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string markPrice = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMarkPrice() {
      markPrice_ = getDefaultInstance().getMarkPrice();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string markPrice = 6;</code>
     * @param value The bytes for markPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMarkPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      markPrice_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object unrealizedPnL_ = "";
    /**
     * <code>string unrealizedPnL = 7;</code>
     * @return The unrealizedPnL.
     */
    public java.lang.String getUnrealizedPnL() {
      java.lang.Object ref = unrealizedPnL_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unrealizedPnL_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string unrealizedPnL = 7;</code>
     * @return The bytes for unrealizedPnL.
     */
    public com.google.protobuf.ByteString
        getUnrealizedPnLBytes() {
      java.lang.Object ref = unrealizedPnL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unrealizedPnL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string unrealizedPnL = 7;</code>
     * @param value The unrealizedPnL to set.
     * @return This builder for chaining.
     */
    public Builder setUnrealizedPnL(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      unrealizedPnL_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string unrealizedPnL = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnrealizedPnL() {
      unrealizedPnL_ = getDefaultInstance().getUnrealizedPnL();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string unrealizedPnL = 7;</code>
     * @param value The bytes for unrealizedPnL to set.
     * @return This builder for chaining.
     */
    public Builder setUnrealizedPnLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      unrealizedPnL_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:market.PositionMessage)
  }

  // @@protoc_insertion_point(class_scope:market.PositionMessage)
  private static final com.demo.proto.market.PositionMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.demo.proto.market.PositionMessage();
  }

  public static com.demo.proto.market.PositionMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PositionMessage>
      PARSER = new com.google.protobuf.AbstractParser<PositionMessage>() {
    @java.lang.Override
    public PositionMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PositionMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PositionMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.demo.proto.market.PositionMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

