// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: utils/protos/market.proto
// Protobuf Java Version: 4.35.0

package com.demo.proto.market;

@com.google.protobuf.Generated
public interface QuoteMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:market.QuoteMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string bid = 3;</code>
   * @return The bid.
   */
  java.lang.String getBid();
  /**
   * <code>string bid = 3;</code>
   * @return The bytes for bid.
   */
  com.google.protobuf.ByteString
      getBidBytes();

  /**
   * <code>string ask = 4;</code>
   * @return The ask.
   */
  java.lang.String getAsk();
  /**
   * <code>string ask = 4;</code>
   * @return The bytes for ask.
   */
  com.google.protobuf.ByteString
      getAskBytes();

  /**
   * <code>string last = 5;</code>
   * @return The last.
   */
  java.lang.String getLast();
  /**
   * <code>string last = 5;</code>
   * @return The bytes for last.
   */
  com.google.protobuf.ByteString
      getLastBytes();

  /**
   * <code>int64 volume24h = 6;</code>
   * @return The volume24h.
   */
  long getVolume24H();

  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
